[package]
name = "e2gt"
version = "0.1.0"
authors = ["Richard Leek <richard@richardleek.com>"]
edition = "2018"

[features]
use_serde = ["serde"]

[dependencies]
byteorder = "1.4.2"
serde = { version = "1.0", features = ["derive"], optional = true }
