[package]
name = "e2gt"
version = "0.1.0"
authors = ["Richard Leek <richard@richardleek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.2"
